sudo: required
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  app: cryptic-chamber-12353
  api_key:
    secure: WsPABWeDVDhytS3AJKhIQBEFU1d+2xHDBfi3BdHT2MBIHL2YNhUfXR16gHQSza9ket2uFb1oAIDdm/aBIsPnRfYHug24CxckMWFee93GEX8bOKWYC1yiKfmq2+7WpI/KDLaISXSePTGmroH5NQ4zWVMXSgFVc1uToRhUzSTj2icwXFn0ogkbIxwmWNHSOhPt1nBoBKRnRF8mshPF4K5/KHDIkBwQWxhMIegc8Swn5GWlWwXR0m2bp/i/pz1TX9M3jRenEQyuW6lc6tCpdsc6QtSrE+xUlwY3Wq1VAIU9QU0noIwQPVU914U9xGwhD42PnfZQapCZobA5FfsfrMVPUCK4gXk2NtGFGiX+VJE5Rz5wBT9qcd+laz2us7H8eJbqS7Py7MSZWfYkTdfvnVCLYN6Len00LvTsUdhB4G9VpGkgvaZe8S+We0BkkI8bICmQFv2BhxNSPLS2qE+LzBdpVyEZw/pfCW8WAGIBQ6sIYGfkj54ozU4QiIUDGVe0sRgnWGlgqD/E8+kJtc4xsmwurPbyQif5caLAFJK2Dl1UD+HWaFBvH76dPuqHs254oywOlNtp6XH7GU4CDbYBxk9x0dzv6mNTII0GfyLttZuZ/yOa6g8fw8wbSjSv7kYWS7kr0ABvTY/y5Z3nSVBGZoNuP4ym6OMK9PsEUjwXoOOixJI=
env:
  global:
    - secure: h1miXTIXIqXNSafL4H/lQIT5tLTEH2gwT0m01aoWiObiJx74daE3uAADZsRREL2NK5AwTJfPrlApulVMj3boZkjCo28FydV/RkoXWespDMMEw2g5gPJX5QsX3gUj+Je3/NlCoLSjqS3EDaoiyYQgLzQVZEibU4aPEdi/wUXWi+KtVjNCJmZNW0wL4h0uYznMbUicUMUe6KowHlYMyOc/gUyTkbuMM7Gmp+G/jtKjaLYnd+eJULp2MqZRkZbxrAIisKU9niFOpSTqJGYz5tHdG7TE3BToeZo12unzmmLlhDK7sCanTRrDyrCSmhJe1FL1D8TD3dkCwg7crydUPgUgMs7HP0ww9jziFLKr8X7U437WC2tu1jQQHApm7QFE3hVNo9e/HfFfoSh5dJ2ItOKE5lrACMJXb2cvFbMsmq3FHPZ5z18JF9WXqIsfuf3YwEQUQz0f+AIUTSYwLSpgeXOSVg82lmZ47QtFf4GG22XqyHVmPyFce9yb2Id6sgmFkpwBc0NqeYpO0SztHq4hiDNr0T4zwwDU339QgpCVt6u2uO77e4dXSeqk3ypeh90/hTawrYmbMAsoNyaakAAbcco4tubyyUxRVuGJhhetvhXUEFGFrAw3QckUop9je3IOQsn8ldKfF317y+T2XlqhvAcQFf091B29j7jDjuEtPkRVH58=
    - secure: LD06A4XMzSeCJtN4k4NN2Itzj3j8Pg2cvowIekcv8VuopziRizJdR2eAZuieoGy/2YK7GLWhmZT2FHmLpBESiMZXtXjxcPIJ6VM0cEEgkfAVXqMxXDbuaI4mzOuTSrpb8z57kZ4AeTSG0h+1T83zRwJ40rRqQodYnmz6k64E/z5ldZanh/3mnILijbXSagOMZsqE/QeBu2khNwKKYaOKJ1Bxe5li7TFJZkXB2qLjvKAoPRX6d8Fd3h/69so6BpaIK+QfaaeVMvB9VEq0t82rUu3PVTukfA5cDHbB406NbKkvGnfHb03wK6MuYbBsqjubGtrsHWv2SuUjgiZ6qPHzClAB8IpXAdZOPghrOdU/jkkWUR5GivPKJQKGaJOU3cYnosnsQnckYf+PVqR1utKUAFnpbahUwToKF6gKSbxj4Hk6Ms5zXLBbq0P+ThrjqpLe3ufR7nlO0tTSgTd2xzQlWtzS5cZTTH78tR4h0uYNI75SIgESzA/bC2MDFErJhvh/IswNtoM1iQl9gUGXUKijeJpV9VlNivcNJL5uqo7chbCsu0oOLGYkLalq+fitXAYiD9gI+Mg0gTzx0OSHP8Tm7ITy5tHF3CgMCIw3Um7aE1OWJfysp/Gs/QHJIxUOScx36EmxVepg8/Z8LctUEbqPaVtGpKKLZMSAHOHohqHtcMs=
  matrix:
