language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  api_key:
    secure: WsPABWeDVDhytS3AJKhIQBEFU1d+2xHDBfi3BdHT2MBIHL2YNhUfXR16gHQSza9ket2uFb1oAIDdm/aBIsPnRfYHug24CxckMWFee93GEX8bOKWYC1yiKfmq2+7WpI/KDLaISXSePTGmroH5NQ4zWVMXSgFVc1uToRhUzSTj2icwXFn0ogkbIxwmWNHSOhPt1nBoBKRnRF8mshPF4K5/KHDIkBwQWxhMIegc8Swn5GWlWwXR0m2bp/i/pz1TX9M3jRenEQyuW6lc6tCpdsc6QtSrE+xUlwY3Wq1VAIU9QU0noIwQPVU914U9xGwhD42PnfZQapCZobA5FfsfrMVPUCK4gXk2NtGFGiX+VJE5Rz5wBT9qcd+laz2us7H8eJbqS7Py7MSZWfYkTdfvnVCLYN6Len00LvTsUdhB4G9VpGkgvaZe8S+We0BkkI8bICmQFv2BhxNSPLS2qE+LzBdpVyEZw/pfCW8WAGIBQ6sIYGfkj54ozU4QiIUDGVe0sRgnWGlgqD/E8+kJtc4xsmwurPbyQif5caLAFJK2Dl1UD+HWaFBvH76dPuqHs254oywOlNtp6XH7GU4CDbYBxk9x0dzv6mNTII0GfyLttZuZ/yOa6g8fw8wbSjSv7kYWS7kr0ABvTY/y5Z3nSVBGZoNuP4ym6OMK9PsEUjwXoOOixJI=
